### ISSUE TITLE
Support for PPC64le

### ISSUE THREAD

**Issue by Richard-Rogalski** [Amanieu/corosensei#18]
Hello!

I'd like to get this working on PPC64. I tried getting something going, but all I get is this:

```
error[E0658]: inline assembly is not stable yet on this architecture
error: `clobber_abi` is not supported on this target
```

Looking at the loong PR, there's a way to to use the unstable inline assembly, but what about this clobber_abi thing? [This](https://doc.rust-lang.org/nightly/unstable-book/language-features/asm-experimental-arch.html) has "only clobbers" under ppc, which makes me thing it should work?

Also, would endianness matter here? I mostly want support for PPC64le, but would the same code work for PPC64(be)?

Thanks for any help!!

**Comment by Amanieu** [comment]
`clobber_abi` is optional, it's just a way to avoid listing all possible registers as clobbers. However it would be nice to have support for it added in the Rust compiler. As you can see in https://github.com/rust-lang/rust/pull/111237, it's not too difficult.

Endianness does not matter here. For example, the ARM/AArch64 code works fine in either endianess.

**Comment by rheaplex** [comment]
@Richard-Rogalski heya did you get any further with this? 😺

**Comment by Pratikt2312** [comment]
@Amanieu I also ran into the issues while attempting build of coronsense 0.1.4 on ppc64le arch. (Rhel 9.3). Are there any updates on adding support for ppc64le?

**Comment by Richard-Rogalski** [comment]
hello, i have a half complete PR for adding the necessary features into rustc. As far as i know, the only thing missing is tests, which I got too burnt out to finish. I’m not sure if I pushed my latest changes, I don’t think so. I’ll try to do that tonight, and if anyone wants to add the tests they’re more than welcome to

Oct 8, 2024 at 05:52 by ***@***.***:

**Comment by Amanieu** [comment]
Thanks @Richard-Rogalski! I'd be happy to start reviewing your PR even if it's incomplete.

**Comment by Amanieu** [comment]
Actually there seems to be another PR for that: https://github.com/rust-lang/rust/pull/131341

**Comment by prasanna-marathe** [comment]
Hi, corosensei build is still failing on Power arch for command _cargo build --target powerpc64le-unknown-linux-gnu_

```
error: Unsupported target
   --> src/arch/mod.rs:168:9
    |
168 |         compile_error!("Unsupported target");
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: Unsupported target
   --> src/stack/valgrind.rs:100:9
    |
100 |         compile_error!("Unsupported target");
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
Request to share if there is any further update  Thanks.

**Comment by prasanna-marathe** [comment]
Hi @Richard-Rogalski 
Are you able to build corosensei module on ppc64le. If yes can you please share steps to build it on ppc64le platform. Thanks.
I am facing issue with below error:


```
error: Unsupported target
   --> src/arch/mod.rs:168:9
    |
168 |         compile_error!("Unsupported target");
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: Unsupported target
   --> src/stack/valgrind.rs:100:9
    |
100 |         compile_error!("Unsupported target");
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

Environment:
# rustc -V
rustc 1.85.0 (4d91de4e4 2025-02-17)
# cargo -V
cargo 1.85.0 (d73d2caf9 2024-12-31)

command used:
#cargo build --target powerpc64le-unknown-linux-gnu

**Comment by Amanieu** [comment]
Rust now has inline assembly support for PPC, but this crate still needs to be ported to PPC, including the inline assembly parts. I am not personally familiar with PPC assembly, but I am happy to mentor anyone who is interested in working on it. I would recommend using the AArch64 implementation as a baseline.

**Comment by xingxue-ibm** [comment]
Are there `corosensei` design documents in addition to the comments and inline documentation in the source code?

**Comment by Amanieu** [comment]
No, the design is only documented in the code comments. The x86_64 back-end has the most documentation to help you understand the code. However for the implementation itself it might be better to start from the AArch64 implementation as a based since it is closer to PPC.

**Comment by Amanieu** [comment]
Sure, that's fine.

**Comment by xingxue-ibm** [comment]
Should we close this issue now that PowerPC64 ELF is supported?
